spring.application.name=FocusFlare
spring.data.mongodb.uri=mongodb://localhost:27017/FocusFlare
spring.data.mongodb.database=FocusFlare
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123
